# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backfill jobs

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    environment: CI
    steps:
    - uses: actions/checkout@v3
    - run: yarn install
    - run: |
          touch .env
          echo TWITTER_SECRET=${{ secrets.TWITTER_SECRET }} > .env
          cat .env
    - run: node backfill-scraper.js
      env:
        TWITTER_SECRET: ${{ secrets.TWITTER_SECRET }}
